apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: training
  namespace: default
spec:
  components:
  - name: aidemo
    type: training
    properties:
      image: fogdong/aidemo:v1.0
      framework: tensorflow
      env:
        - name: VERSION
          value: "v1"
      storage:
        - name: "my-pvc"
          mountPath: "/opt/model"
