apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: style-model
  namespace: default
spec:
  components:
  - name: cp-style-model
    type: task
    properties:
      image: fogdong/tfmodel
    traits:
      - type: storage
        properties:
          pvc:
            - name: style-model
              mountPath: /mnt